/*
 * ACME Reviews - PSIDI
 *
 * Swagger proposed server for the Review Product infrastructure at ACME .Inc
 *
 * API version: 0.1
 * Contact: 1171071@isep.ipp.pt
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"
	//	"github.com/joho/godotenv"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
)

func main() {
	log.Printf("Server started")
	router := NewRouter()
	//	godotenv.Load(".env")
	port := os.Getenv("PORT")

	//port := "8080"
	log.Println(port)
	log.Fatal(http.ListenAndServe(":"+port, router))
	//log.Fatal(http.ListenAndServe(":8080", router))
}
